; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.3.0 on Wed Aug 11 2021 08:50:32 GMT+0200 (Mitteleuropäische Sommerzeit)
M280 P0 S10 ; deploy BLTouch

