; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.0 on Wed Aug 11 2021 08:50:32 GMT+0200 (Mitteleuropäische Sommerzeit)

